---
title: 'Immigration attitudes: the role of economic and cultural threat'
output:
  pdf_document: default
  html_document: default
---

<style type="text/css">
    ol { list-style-type: lower-alpha; }
</style>

## Instructions 

Why do the majority of voters in the U.S. and other developed countries oppose increased immigration? According to the conventional wisdom and many economic theories, people simply do not want to face additional competition on the labor market (*economic threat* hypothesis). Nonetheless, most comprehensive empirical tests have failed to confirm this hypothesis and it appears that people often support policies that are against their personal economic interest. At the same time, there has been growing evidence that immigration attitudes are rather influenced by various deep-rooted ethnic and cultural stereotypes (*cultural threat* hypothesis). Given the prominence of workers' economic concerns in the political discourse, how can these findings be reconciled? 

This exercise is based in part on Malhotra, N., Margalit, Y. and Mo, C.H., 2013. "[Economic Explanations for Opposition to Immigration: Distinguishing between Prevalence and Conditional Impact](https://dx.doi.org/10.1111/ajps.12012)." *American Journal of Political Science*, Vol. 38, No. 3, pp. 393-433.

The authors argue that, while job competition is not a prevalent threat and therefore may not be detected by aggregating survey responses, its *conditional* impact in selected industries may be quite sizable. To test their hypothesis, they conduct a unique survey of Americans' attitudes toward H-1B visas. The plurality of H-1B visas are occupied by Indian immigrants, who are skilled but ethnically distinct, which enables the authors to measure a specific skill set (high technology) that is threatened by a particular type of immigrant (H-1B visa holders). The data set `immig.csv` has the following variables:

-----------------------------------------------------------------------------------------
 Name                             Description
 -------------------------------- -------------------------------------------------------
 `age`                            Age (in years)
 
 `female`                         `1` indicates female; `0` indicates male
 
 `employed`                       `1` indicates employed; `0` indicates unemployed  
 
 `nontech.whitcol`                `1` indicates non-tech white-collar work (e.g., law)
 
 `tech.whitcol`                   `1` indicates high-technology work
 
 `expl.prejud`                    Explicit negative stereotypes about Indians (continuous 
                                  scale, 0-1)
 
 `impl.prejud`                    Implicit bias against Indian Americans (continuous scale, 
                                  0-1)
                                  
 `h1bvis.supp`                    Support for increasing H-1B visas (5-point scale, 0-1)
 
 `indimm.supp`                    Support for increasing Indian immigration (5-point scale, 
                                  0-1)
-----------------------------------------------------------------------------------------

The main outcome of interest (`h1bvis.supp`) was measured as a following survey item: "Some people have proposed that the U.S. government should increase the number of H-1B visas, which are allowances for U.S. companies to hire workers from foreign countries to work in highly skilled occupations (such as engineering, computer programming, and high-technology). Do you think the U.S. should increase, decrease, or keep about the same number of H-1B visas?" Another outcome (`indimm.supp`) similarly asked about the "the number of immigrants from India." Both variables have the following response options: `0` = "decrease a great deal", `0.25` = "decrease a little", `0.5` = "keep about the same", `0.75` = "increase a little", `1` = "increase a great deal".

To measure explicit stereotypes (`expl.prejud`), respondents were asked to evaluate Indians on a series of traits: capable, polite, hardworking, hygienic, and trustworthy. All responses were then used to create a scale lying between `0` (only positive traits of Indians) to `1` (no positive traits of Indians). Implicit bias (`impl.prejud`) is measured via the *Implicit Association Test* (IAT) which is an experimental method designed to gauge the strength of associations linking social categories (e.g., European vs Indian American) to evaluative anchors (e.g., good vs bad). Individual who are prejudiced against Indians should be quicker at making classifications of faces and words when *European American* (*Indian American*) is paired with *good* (*bad*) than when *European American* (*Indian American*) is paired with *bad* (*good*). If you want, you can test yourself [here](https://implicit.harvard.edu/implicit/takeatest.html).

Before we get to the data, let's first get to know how to use RMarkdown a little better.

## Question 1: A little markdown

Write a sentence that, once knitted, will have a word in italics, a word in bold, a superscript, a strikethrough, and a hyperlink to the RStudio website (www.rstudio.com).



## Question 2: Using code chunks

Create a code chunk and write some code to do the operation `3 + 4`.







## Question 3: Knitting

Compile your work so far into a PDF document by selecting "Knit to PDF" from the Knit dropdown menu at the top of your screen. A window with your PDF should pop up when complete.


## Question 4: Reading data into R

Before we can get started working with data, we first need to load the data into R. Datasets can come in many file types, but the most common is a CSV, which stands for "comma-separated values". Use the `read.csv()` function to read your data into R and call it `rosca`.





## Question 5: Checking out the data

Use the `head()` function to view the first several rows of the data. If you want, change the number of observations the function returns.





## Question 6: Histograms

Let's get a sense for the distribution of explicit prejudice in the data. Make a histogram of the `expl.prejud` variable using ggplot, and be sure to label the axes. Make another histogram of implicit prejudice and compare the two plots.






## Question 7: Scatterplots

Make a scatterplot of age on the x-axis and implicit prejudice on the y-axis. What do we see?





## Question 8: Adding a line of best fit

It's a bit difficult to visually verify the relationship between these two variables. Luckily, the `ggplot2` package makes it easy to add a line of best fit to your data. Add `geom_smooth()` to your plot from question 7 to see the line of best fit. Take a look at the documentation for `geom_smooth()` and play around with the settings a little bit if you want.





## Question 9: Subgroup plots

Now make a scatterplot of age on the x-axis and implicit prejudice on the y-axis, this time split by whether or not the respondent is female. Use the `facet_wrap()` geom to create a plot with two panels, one for female respondents and one for other respondents.





## Question 10: Referencing R objects in your text

Create another code chunk and create a new object called `my_num` set to your favorite number. Below the code chunk, use the following convention to reference your favorite number: 'r my_num' (but replace the single quotes with backticks).





